# Generated by Django 4.1.1 on 2024-03-28 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='perfiles_plantas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=100)),
                ('humidity_excellent', models.IntegerField()),
                ('humidity_regular', models.IntegerField()),
                ('humidity_bad', models.IntegerField()),
                ('intensity_excellent', models.IntegerField()),
                ('intensity_regular', models.IntegerField()),
                ('intensity_bad', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='historial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(default=' ', max_length=30)),
                ('humidity', models.FloatField(default=0)),
                ('intensity', models.FloatField(default=0)),
                ('owner', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.perfiles_plantas')),
            ],
        ),
    ]
