# Generated by Django 4.1.1 on 2024-03-28 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_alerta_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='id_historial',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='dashboard.historial'),
        ),
    ]
