# Generated by Django 4.1.1 on 2024-03-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alerta_id_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='id_historial',
            field=models.IntegerField(default='1'),
        ),
    ]
