# Generated by Django 4.1.1 on 2024-04-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_consejos'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiles_plantas',
            name='comentario',
            field=models.CharField(default='', max_length=150),
        ),
    ]
