# Generated by Django 4.1.1 on 2024-04-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_consejo_consejo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='consejo',
            name='titulo',
            field=models.TextField(default='Sin titulo'),
        ),
    ]
