# Generated by Django 4.1.1 on 2024-04-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_consejo_options_alter_consejo_texto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='beneficios_dashboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(default='Sin titulo', max_length=150)),
                ('texto', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name': 'Beneficios_dashboard',
            },
        ),
    ]
